### Login user and get token
POST  http://localhost:3000/cowid-19/user
@Variables = 
{ 
    "mobile": "6353653848",
    "password": "addweb123" 
}

### Get authenticated user using the token
GET  http://localhost:3000/cowid-19/user
x-auth-token: {{token}}