### Schedule dose api.
POST  http://localhost:3000/cowid-19/schedule
x-auth-token: {{token}}
@Variables = 
{ 
    "refId":"1638161689160",
    "address": "Rajiv gandhi bhavan",
    "vaccineType":"cowaxin",
    "age":"18 & above",
    "cost":"free",
    "date":"21 july 2021",
    "timeSlot":"9 to 12"
}